/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}



fun sumar(a: Int, b: Int) = a + b



fun main() {


    println(sumar(2, 3))


}
